name: ImusEnchants
version: '${project.version}'
main: me.imu.imusenchants.ImusEnchants
api-version: '1.20'
depend:
  - imusAPI
commands:
  imusenchants:
    description: ImusEnchants
    usage: /<command>
    aliases:
      - ien