name: imusCasino
author: imukuppikorva
version: 1.0
main: imu.iCasino.Main.CasinoMain
description: imus casino plugin
api-version: 1.16
depend: [Vault, imusAPI]
commands:
   ic:
     description: casino menu
     usage: 

   