name: ImusChallenges
version: '${project.version}'
main: me.imu.imuschallenges.ImusChallenges
api-version: 1.20
authors: [ imukuppikorvaa ]
description: The challanges for drevaria server
depend:
  - imusAPI
commands:
  imuschallenges:
    description: imusChallenges
    usage: /<command>
    aliases:
      - ic
