name: WorldRestore
author: bullterrier292
version: 3.0
main: me.bullterrier292.WorldRestore.WorldRestore
description: WorldRestore!
api-version: 1.13
depend: [WorldGuard]

commands:
   cord:
     description: Gives cordinates to others!
     usage:  /<command>
   wr:
     description: wr
     usage: /<command>
   
      