name: imusAPI
author: imukuppikorva
version: 1.1
main: imu.iAPI.Main.ImusAPI
description: imus own api
softdepend: [ProtocolLib]
api-version: 1.20
commands:
   ia:
     description: ia
     usage: /<command>
