name: GeneralStore
author: imukuppikorva
version: 1.0
main: imu.GeneralStore.main.Main
description: General Store
api-version: 1.15
commands:
   gs:
     description: GeneralStore
     usage:  /<command>
      