name: imusGS
author: imu
version: 1.0
main: imu.GS.Main.Main
api-version: 1.18
softdepend: [Vault, ImusAPI]
commands:
   gs:
     description: GS
     usage: /<command>
   gs create shop:
     description: Create Shop
     usage: /<command>
   g:
     description: G
     usage: /<command>
   