name: imusMiniGames
author: imukuppikorva
version: 1.0
main: imu.iMiniGames.Main.ImusMiniGames
description: imusMiniGames
api-version: 1.19
softdepend: [imusAPI,Vault]
commands:
   img:
     description: Create arenas
     usage: /<command> [spleef] arenaName
   mg:
     description: Player commands
     usage: /<command> [spleef]
   