name: Abi
author: imu
version: 1.0
main: imu.AccountBoundItems.main.Main
description: Account bound items
api-version: 1.15
softdepend: [Vault]
commands:
   abi:
     description: Commands to manage binds
     usage: /<command>
   abi bind:
     description: Bind item in your hand to your name.
     usage: /<command>
   abi reload:
     description: Reload all configs
     usage: /<command>
   abi wait:
     description: Bind item in your hand what will wait anything to happen and bind it to owner.
     usage: /<command>
   abi use:
     description: Bind item in your hand to use. When item is used it will be bind to the user.
     usage: /<command>
   abi broken:
     description: Set item broken in your hand.
     usage: /<command>
   abi unbind:
     description: Unbind item in your hand.
     usage: /<command>
   abi repair:
     description: Repair item in your hand without cost.
     usage: /<command>
   abi repair all:
     description: Repair all items in your inventory without cost.
     usage: /<command>
   abi repair cost:
     description: NPC command. First time give you price of repair. Second time same command repair the item with cost.
     usage: /<command>
   abi bind cost: 
     description:  NPC command. First time give you price of bind. Second time same command bind the item with cost.
     usage: /<command>
   abi setprice:
     description: Set item unique price. Item price will not be effect any automated calculations.
     usage: /<command>
   abi money:
     description: Gives you money check amount of given
     usage: /<command> <amount>
   abi redeem:
     description: Gives money back from check in your hand
     usage: /<command>