name: WorldRestore
version: 1.0
author: bullterrier292
main: me.bullterrier292.WorldRestore
commands:
   wr:
       description: Restores world from default_world 
       aliases: [worldrestore, rw]
       usage: "Usage: /<command> name"
   wrdc:
       description: Restores used chunks top to bottom
       aliases: [wrdetectedchunks,rwdetectedchunks,rwdc]
       usage: "Usage: /<command>"
   wrdsc:
       description: Restores used chunks y=55 to y=256
       aliases: [wrdetectedsurfacechunks,rwdetectedsurfacechunks,rwdsc]
       usage: /<command>
   wrautoc:
       description: Restores automatically used chunks given expired time
       aliases: [rwautoc,wrautodetectedchunks]
       usage: "Usage: /<command> timeInMs"
   wrautosc:
       description: Restores automatically used surface chunks given expired time
       aliases: [rwautosc,wrautosurfacechunks]
       usage: "Usage: /<command> timeInMs"
   wrthis:
       description: Restores chunk below you, WARNING Dont check players in this chunk
       aliases: [rwthis]
       usage: "Usage: /<command>"
   wrstop:
       description: Stops /wr command
       aliases: [rwstop]
       usage: "Usage: /<command>"
   wrset:
       description: Sets wr chunkpoits, takes chunk below you /wr name
       aliases: [rwset]
       usage: "Usage: /<command> Name Direction(for example ES) HowManyChunksOnce HowManySecondsDelayBetweenUpdates HowManyChunks(MultiliedItself)"
   wrhelp:
       description: Gives you all info about WorldRestore
       aliases: [rwhelp, helpwr, wr help]
       usage: /<command>
   wrthat:
       description: Fix chunk what is given
       aliases: [rwthat]
       usage: "Usage: /wrthat chunkX chunkZ bottomY topY"
    
 