name: HomeTele
author: imukuppikorva
version: 1.0
main: imu.HomeTele.Main
description: defPlate
api-version: 1.15
commands:
   sethome:
     description: You can set home
     usage:  /<command>
   home:
      description: Teleports you to home
      usage: /<command>
   homelist:
      description: Shows homes
      usage: /<command>
      