name: UltimateCustomItems
author: imukuppikorva
version: 1.0
main: imu.UCI.main.Main
description: UltimateCustomItems
api-version: 1.15
#softdepend: [WorldEdit,WorldGuard]
commands:
   uci:
     description: UltimateCustomItems
     usage:  /<command>     