name: TokenTp
author: imukuppikorva
version: 1.0
main: imu.TokenTp.main.Main
description: Teleport tokens
api-version: 1.16
commands:
   ttp:
     description: Nothing here
     usage:  /<command>
     commands:
   tttp:
     description: Nothing here
     usage: /<command>
     commands: 
   ttp spawn card:
     description: Spawn token card. Gives options.
     usage: /<command>
     commands:
   ttp spawn base:
     description: Spawn token base
     usage: /<command>
     commands:
   ttp spawn token:
     description: Spawn usable token, gives options.
     usage: /<command>
     commands:
   ttp set desc:
     description: Set any token description text
     usage: /<command> {text}
     commands:
   ttp set dest:
     description: Set any token destination text
     usage: /<command> {text}
     commands:
   ttp reload:
     description: Reload configs
     usage: /<command>
     commands: 
     
     